import Head from "next/head";
import Toolkit from "../components/Toolkit";
import Workspace from "../components/Workspace";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yuria Movie Poster Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolkit className={styles.toolkit} />
      <div className="divider vertical thick"></div>
      <Workspace className={styles.workspace} />
    </div>
  );
}
